language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY_VERSION=origin/master

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - yes '' | pecl install -f ssh2-beta
  - php -m | grep ssh2
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --configuration phpunit.travis.xml